GET http://localhost:3003/api/blogs HTTP/1.1

###
GET http://localhost:3003/api/blogs/63d043b66f9448c64893fc79 HTTP/1.1

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "Finance Blog",
    "author": "Laura White",
    "url": "url",
    "likes": 66303
}

###
PUT http://localhost:3003/api/blogs/63d3fd7f46467c341e318b21 HTTP/1.1
Content-Type: application/json

{
    "title": "Finance Blog",
    "author": "Laura White",
    "url": "url",
    "likes": 82240
}

###
DELETE http://localhost:3003/api/blogs/63d158e00ed7dc6f47a35d4d HTTP/1.1